---
- name: Install extra terminfo definitions
  hosts: all
  become: yes
  tasks:
    - include_role:
        name: extra_terminfo
      vars:
        terminal_type: "alacritty"
    - include_role:
        name: extra_terminfo
      vars:
        terminal_type: "ghostty"
    - include_role:
        name: extra_terminfo
      vars:
        terminal_type: "kitty"
